# Generated by Django 3.0.6 on 2020-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('Username', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=30)),
            ],
        ),
    ]
